pull_request_rules:
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Build
      - status-success=Lint
    actions:
      merge:
        method: squash