addSbtPlugin("org.typelevel"  % "sbt-tpolecat"   % "0.5.2")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.6")
addSbtPlugin("com.github.sbt" % "sbt-header"     % "5.11.0")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.14.5")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.2")
