addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.4.4")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"     % "5.10.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.11.1")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release" % "1.5.12")
